const NEETCODE_150_PROBLEMS = [
  { order: 1, title: "Contains Duplicate", topic: "Arrays & Hashing", difficulty: "Easy", leetcodeLink: "https://leetcode.com/problems/contains-duplicate/" },
  { order: 2, title: "Valid Anagram", topic: "Arrays & Hashing", difficulty: "Easy", leetcodeLink: "https://leetcode.com/problems/valid-anagram/" },
  { order: 3, title: "Two Sum", topic: "Arrays & Hashing", difficulty: "Easy", leetcodeLink: "https://leetcode.com/problems/two-sum/" },
  { order: 4, title: "Group Anagrams", topic: "Arrays & Hashing", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/group-anagrams/" },
  { order: 5, title: "Top K Frequent Elements", topic: "Arrays & Hashing", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/top-k-frequent-elements/" },
  { order: 6, title: "Product of Array Except Self", topic: "Arrays & Hashing", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/product-of-array-except-self/" },
  { order: 7, title: "Valid Sudoku", topic: "Arrays & Hashing", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/valid-sudoku/" },
  { order: 8, title: "Encode and Decode Strings", topic: "Arrays & Hashing", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/encode-and-decode-strings/" },
  { order: 9, title: "Longest Consecutive Sequence", topic: "Arrays & Hashing", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/longest-consecutive-sequence/" },
  { order: 10, title: "Valid Palindrome", topic: "Two Pointers", difficulty: "Easy", leetcodeLink: "https://leetcode.com/problems/valid-palindrome/" },
  { order: 11, title: "Two Sum II - Input Array Is Sorted", topic: "Two Pointers", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/" },
  { order: 12, title: "3Sum", topic: "Two Pointers", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/3sum/" },
  { order: 13, title: "Container With Most Water", topic: "Two Pointers", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/container-with-most-water/" },
  { order: 14, title: "Trapping Rain Water", topic: "Two Pointers", difficulty: "Hard", leetcodeLink: "https://leetcode.com/problems/trapping-rain-water/" },
  { order: 15, title: "Best Time to Buy and Sell Stock", topic: "Sliding Window", difficulty: "Easy", leetcodeLink: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/" },
  { order: 16, title: "Longest Substring Without Repeating Characters", topic: "Sliding Window", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/longest-substring-without-repeating-characters/" },
  { order: 17, title: "Longest Repeating Character Replacement", topic: "Sliding Window", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/longest-repeating-character-replacement/" },
  { order: 18, title: "Permutation in String", topic: "Sliding Window", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/permutation-in-string/" },
  { order: 19, title: "Minimum Window Substring", topic: "Sliding Window", difficulty: "Hard", leetcodeLink: "https://leetcode.com/problems/minimum-window-substring/" },
  { order: 20, title: "Sliding Window Maximum", topic: "Sliding Window", difficulty: "Hard", leetcodeLink: "https://leetcode.com/problems/sliding-window-maximum/" },
  { order: 21, title: "Valid Parentheses", topic: "Stack", difficulty: "Easy", leetcodeLink: "https://leetcode.com/problems/valid-parentheses/" },
  { order: 22, title: "Min Stack", topic: "Stack", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/min-stack/" },
  { order: 23, title: "Evaluate Reverse Polish Notation", topic: "Stack", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/evaluate-reverse-polish-notation/" },
  { order: 24, title: "Generate Parentheses", topic: "Stack", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/generate-parentheses/" },
  { order: 25, title: "Daily Temperatures", topic: "Stack", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/daily-temperatures/" },
  { order: 26, title: "Car Fleet", topic: "Stack", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/car-fleet/" },
  { order: 27, title: "Binary Search", topic: "Binary Search", difficulty: "Easy", leetcodeLink: "https://leetcode.com/problems/binary-search/" },
  { order: 28, title: "Search a 2D Matrix", topic: "Binary Search", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/search-a-2d-matrix/" },
  { order: 29, title: "Koko Eating Bananas", topic: "Binary Search", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/koko-eating-bananas/" },
  { order: 30, title: "Find Minimum in Rotated Sorted Array", topic: "Binary Search", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/" },
  { order: 31, title: "Search in Rotated Sorted Array", topic: "Binary Search", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/search-in-rotated-sorted-array/" },
  { order: 32, title: "Time Based Key-Value Store", topic: "Binary Search", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/time-based-key-value-store/" },
  { order: 33, title: "Median of Two Sorted Arrays", topic: "Binary Search", difficulty: "Hard", leetcodeLink: "https://leetcode.com/problems/median-of-two-sorted-arrays/" },
  { order: 34, title: "Reverse Linked List", topic: "Linked List", difficulty: "Easy", leetcodeLink: "https://leetcode.com/problems/reverse-linked-list/" },
  { order: 35, title: "Merge Two Sorted Lists", topic: "Linked List", difficulty: "Easy", leetcodeLink: "https://leetcode.com/problems/merge-two-sorted-lists/" },
  { order: 36, title: "Reorder List", topic: "Linked List", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/reorder-list/" },
  { order: 37, title: "Remove Nth Node From End of List", topic: "Linked List", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/remove-nth-node-from-end-of-list/" },
  { order: 38, title: "Copy List with Random Pointer", topic: "Linked List", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/copy-list-with-random-pointer/" },
  { order: 39, title: "Add Two Numbers", topic: "Linked List", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/add-two-numbers/" },
  { order: 40, title: "Linked List Cycle", topic: "Linked List", difficulty: "Easy", leetcodeLink: "https://leetcode.com/problems/linked-list-cycle/" },
  { order: 41, title: "Find the Duplicate Number", topic: "Linked List", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/find-the-duplicate-number/" },
  { order: 42, title: "LRU Cache", topic: "Linked List", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/lru-cache/" },
  { order: 43, title: "Merge K Sorted Lists", topic: "Linked List", difficulty: "Hard", leetcodeLink: "https://leetcode.com/problems/merge-k-sorted-lists/" },
  { order: 44, title: "Reverse Nodes in K-Group", topic: "Linked List", difficulty: "Hard", leetcodeLink: "https://leetcode.com/problems/reverse-nodes-in-k-group/" },
  { order: 45, title: "Invert Binary Tree", topic: "Trees", difficulty: "Easy", leetcodeLink: "https://leetcode.com/problems/invert-binary-tree/" },
  { order: 46, title: "Maximum Depth of Binary Tree", topic: "Trees", difficulty: "Easy", leetcodeLink: "https://leetcode.com/problems/maximum-depth-of-binary-tree/" },
  { order: 47, title: "Diameter of Binary Tree", topic: "Trees", difficulty: "Easy", leetcodeLink: "https://leetcode.com/problems/diameter-of-binary-tree/" },
  { order: 48, title: "Balanced Binary Tree", topic: "Trees", difficulty: "Easy", leetcodeLink: "https://leetcode.com/problems/balanced-binary-tree/" },
  { order: 49, title: "Same Tree", topic: "Trees", difficulty: "Easy", leetcodeLink: "https://leetcode.com/problems/same-tree/" },
  { order: 50, title: "Subtree of Another Tree", topic: "Trees", difficulty: "Easy", leetcodeLink: "https://leetcode.com/problems/subtree-of-another-tree/" },
  { order: 51, title: "Lowest Common Ancestor of a Binary Search Tree", topic: "Trees", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/" },
  { order: 52, title: "Binary Tree Level Order Traversal", topic: "Trees", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/binary-tree-level-order-traversal/" },
  { order: 53, title: "Binary Tree Right Side View", topic: "Trees", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/binary-tree-right-side-view/" },
  { order: 54, title: "Count Good Nodes in Binary Tree", topic: "Trees", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/count-good-nodes-in-binary-tree/" },
  { order: 55, title: "Validate Binary Search Tree", topic: "Trees", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/validate-binary-search-tree/" },
  { order: 56, title: "Kth Smallest Element in a BST", topic: "Trees", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/kth-smallest-element-in-a-bst/" },
  { order: 57, title: "Construct Binary Tree from Preorder and Inorder Traversal", topic: "Trees", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/" },
  { order: 58, title: "Binary Tree Maximum Path Sum", topic: "Trees", difficulty: "Hard", leetcodeLink: "https://leetcode.com/problems/binary-tree-maximum-path-sum/" },
  { order: 59, title: "Serialize and Deserialize Binary Tree", topic: "Trees", difficulty: "Hard", leetcodeLink: "https://leetcode.com/problems/serialize-and-deserialize-binary-tree/" },
  { order: 60, title: "Kth Largest Element in a Stream", topic: "Heap / Priority Queue", difficulty: "Easy", leetcodeLink: "https://leetcode.com/problems/kth-largest-element-in-a-stream/" },
  { order: 61, title: "Last Stone Weight", topic: "Heap / Priority Queue", difficulty: "Easy", leetcodeLink: "https://leetcode.com/problems/last-stone-weight/" },
  { order: 62, title: "K Closest Points to Origin", topic: "Heap / Priority Queue", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/k-closest-points-to-origin/" },
  { order: 63, title: "Kth Largest Element in an Array", topic: "Heap / Priority Queue", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/kth-largest-element-in-an-array/" },
  { order: 64, title: "Task Scheduler", topic: "Heap / Priority Queue", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/task-scheduler/" },
  { order: 65, title: "Design Twitter", topic: "Heap / Priority Queue", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/design-twitter/" },
  { order: 66, title: "Find Median from Data Stream", topic: "Heap / Priority Queue", difficulty: "Hard", leetcodeLink: "https://leetcode.com/problems/find-median-from-data-stream/" },
  { order: 67, title: "Subsets", topic: "Backtracking", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/subsets/" },
  { order: 68, title: "Combination Sum", topic: "Backtracking", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/combination-sum/" },
  { order: 69, title: "Permutations", topic: "Backtracking", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/permutations/" },
  { order: 70, title: "Subsets II", topic: "Backtracking", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/subsets-ii/" },
  { order: 71, title: "Combination Sum II", topic: "Backtracking", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/combination-sum-ii/" },
  { order: 72, title: "Word Search", topic: "Backtracking", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/word-search/" },
  { order: 73, title: "Palindrome Partitioning", topic: "Backtracking", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/palindrome-partitioning/" },
  { order: 74, title: "Letter Combinations of a Phone Number", topic: "Backtracking", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/letter-combinations-of-a-phone-number/" },
  { order: 75, title: "N-Queens", topic: "Backtracking", difficulty: "Hard", leetcodeLink: "https://leetcode.com/problems/n-queens/" },
  { order: 76, title: "Permutations II", topic: "Backtracking", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/permutations-ii/" },
  { order: 77, title: "Implement Trie (Prefix Tree)", topic: "Tries", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/implement-trie-prefix-tree/" },
  { order: 78, title: "Design Add and Search Words Data Structure", topic: "Tries", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/design-add-and-search-words-data-structure/" },
  { order: 79, title: "Word Search II", topic: "Tries", difficulty: "Hard", leetcodeLink: "https://leetcode.com/problems/word-search-ii/" },
  { order: 80, title: "Number of Islands", topic: "Graphs", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/number-of-islands/" },
  { order: 81, title: "Max Area of Island", topic: "Graphs", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/max-area-of-island/" },
  { order: 82, title: "Clone Graph", topic: "Graphs", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/clone-graph/" },
  { order: 83, title: "Walls and Gates", topic: "Graphs", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/walls-and-gates/" },
  { order: 84, title: "Rotting Oranges", topic: "Graphs", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/rotting-oranges/" },
  { order: 85, title: "Pacific Atlantic Water Flow", topic: "Graphs", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/pacific-atlantic-water-flow/" },
  { order: 86, title: "Surrounded Regions", topic: "Graphs", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/surrounded-regions/" },
  { order: 87, title: "Course Schedule", topic: "Graphs", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/course-schedule/" },
  { order: 88, title: "Course Schedule II", topic: "Graphs", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/course-schedule-ii/" },
  { order: 89, title: "Graph Valid Tree", topic: "Graphs", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/graph-valid-tree/" },
  { order: 90, title: "Number of Connected Components in an Undirected Graph", topic: "Graphs", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph/" },
  { order: 91, title: "Redundant Connection", topic: "Graphs", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/redundant-connection/" },
  { order: 92, title: "Word Ladder", topic: "Graphs", difficulty: "Hard", leetcodeLink: "https://leetcode.com/problems/word-ladder/" },
  { order: 93, title: "Reconstruct Itinerary", topic: "Advanced Graphs", difficulty: "Hard", leetcodeLink: "https://leetcode.com/problems/reconstruct-itinerary/" },
  { order: 94, title: "Min Cost to Connect All Points", topic: "Advanced Graphs", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/min-cost-to-connect-all-points/" },
  { order: 95, title: "Network Delay Time", topic: "Advanced Graphs", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/network-delay-time/" },
  { order: 96, title: "Swim in Rising Water", topic: "Advanced Graphs", difficulty: "Hard", leetcodeLink: "https://leetcode.com/problems/swim-in-rising-water/" },
  { order: 97, title: "Alien Dictionary", topic: "Advanced Graphs", difficulty: "Hard", leetcodeLink: "https://leetcode.com/problems/alien-dictionary/" },
  { order: 98, title: "Cheapest Flights Within K Stops", topic: "Advanced Graphs", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/cheapest-flights-within-k-stops/" },
  { order: 99, title: "Climbing Stairs", topic: "1-D Dynamic Programming", difficulty: "Easy", leetcodeLink: "https://leetcode.com/problems/climbing-stairs/" },
  { order: 100, title: "Min Cost Climbing Stairs", topic: "1-D Dynamic Programming", difficulty: "Easy", leetcodeLink: "https://leetcode.com/problems/min-cost-climbing-stairs/" },
  { order: 101, title: "House Robber", topic: "1-D Dynamic Programming", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/house-robber/" },
  { order: 102, title: "House Robber II", topic: "1-D Dynamic Programming", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/house-robber-ii/" },
  { order: 103, title: "Longest Palindromic Substring", topic: "1-D Dynamic Programming", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/longest-palindromic-substring/" },
  { order: 104, title: "Palindromic Substrings", topic: "1-D Dynamic Programming", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/palindromic-substrings/" },
  { order: 105, title: "Decode Ways", topic: "1-D Dynamic Programming", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/decode-ways/" },
  { order: 106, title: "Coin Change", topic: "1-D Dynamic Programming", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/coin-change/" },
  { order: 107, title: "Maximum Product Subarray", topic: "1-D Dynamic Programming", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/maximum-product-subarray/" },
  { order: 108, title: "Word Break", topic: "1-D Dynamic Programming", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/word-break/" },
  { order: 109, title: "Longest Increasing Subsequence", topic: "1-D Dynamic Programming", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/longest-increasing-subsequence/" },
  { order: 110, title: "Partition Equal Subset Sum", topic: "1-D Dynamic Programming", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/partition-equal-subset-sum/" },
  { order: 111, title: "Unique Paths", topic: "2-D Dynamic Programming", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/unique-paths/" },
  { order: 112, title: "Longest Common Subsequence", topic: "2-D Dynamic Programming", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/longest-common-subsequence/" },
  { order: 113, title: "Best Time to Buy and Sell Stock with Cooldown", topic: "2-D Dynamic Programming", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-cooldown/" },
  { order: 114, title: "Coin Change II", topic: "2-D Dynamic Programming", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/coin-change-ii/" },
  { order: 115, title: "Target Sum", topic: "2-D Dynamic Programming", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/target-sum/" },
  { order: 116, title: "Interleaving String", topic: "2-D Dynamic Programming", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/interleaving-string/" },
  { order: 117, title: "Longest Increasing Path in a Matrix", topic: "2-D Dynamic Programming", difficulty: "Hard", leetcodeLink: "https://leetcode.com/problems/longest-increasing-path-in-a-matrix/" },
  { order: 118, title: "Distinct Subsequences", topic: "2-D Dynamic Programming", difficulty: "Hard", leetcodeLink: "https://leetcode.com/problems/distinct-subsequences/" },
  { order: 119, title: "Edit Distance", topic: "2-D Dynamic Programming", difficulty: "Hard", leetcodeLink: "https://leetcode.com/problems/edit-distance/" },
  { order: 120, title: "Burst Balloons", topic: "2-D Dynamic Programming", difficulty: "Hard", leetcodeLink: "https://leetcode.com/problems/burst-balloons/" },
  { order: 121, title: "Regular Expression Matching", topic: "2-D Dynamic Programming", difficulty: "Hard", leetcodeLink: "https://leetcode.com/problems/regular-expression-matching/" },
  { order: 122, title: "Maximum Subarray", topic: "Greedy", difficulty: "Easy", leetcodeLink: "https://leetcode.com/problems/maximum-subarray/" },
  { order: 123, title: "Jump Game", topic: "Greedy", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/jump-game/" },
  { order: 124, title: "Jump Game II", topic: "Greedy", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/jump-game-ii/" },
  { order: 125, title: "Gas Station", topic: "Greedy", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/gas-station/" },
  { order: 126, title: "Hand of Straights", topic: "Greedy", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/hand-of-straights/" },
  { order: 127, title: "Merge Triplets to Form Target Triplet", topic: "Greedy", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/merge-triplets-to-form-target-triplet/" },
  { order: 128, title: "Partition Labels", topic: "Greedy", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/partition-labels/" },
  { order: 129, title: "Valid Parenthesis String", topic: "Greedy", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/valid-parenthesis-string/" },
  { order: 130, title: "Insert Interval", topic: "Intervals", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/insert-interval/" },
  { order: 131, title: "Merge Intervals", topic: "Intervals", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/merge-intervals/" },
  { order: 132, title: "Non-overlapping Intervals", topic: "Intervals", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/non-overlapping-intervals/" },
  { order: 133, title: "Meeting Rooms", topic: "Intervals", difficulty: "Easy", leetcodeLink: "https://leetcode.com/problems/meeting-rooms/" },
  { order: 134, title: "Meeting Rooms II", topic: "Intervals", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/meeting-rooms-ii/" },
  { order: 135, title: "Minimum Interval to Include Each Query", topic: "Intervals", difficulty: "Hard", leetcodeLink: "https://leetcode.com/problems/minimum-interval-to-include-each-query/" },
  { order: 136, title: "Rotate Image", topic: "Math & Geometry", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/rotate-image/" },
  { order: 137, title: "Spiral Matrix", topic: "Math & Geometry", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/spiral-matrix/" },
  { order: 138, title: "Set Matrix Zeroes", topic: "Math & Geometry", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/set-matrix-zeroes/" },
  { order: 139, title: "Happy Number", topic: "Math & Geometry", difficulty: "Easy", leetcodeLink: "https://leetcode.com/problems/happy-number/" },
  { order: 140, title: "Plus One", topic: "Math & Geometry", difficulty: "Easy", leetcodeLink: "https://leetcode.com/problems/plus-one/" },
  { order: 141, title: "Pow(x, n)", topic: "Math & Geometry", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/powx-n/" },
  { order: 142, title: "Multiply Strings", topic: "Math & Geometry", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/multiply-strings/" },
  { order: 143, title: "Detect Squares", topic: "Math & Geometry", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/detect-squares/" },
  { order: 144, title: "Single Number", topic: "Bit Manipulation", difficulty: "Easy", leetcodeLink: "https://leetcode.com/problems/single-number/" },
  { order: 145, title: "Number of 1 Bits", topic: "Bit Manipulation", difficulty: "Easy", leetcodeLink: "https://leetcode.com/problems/number-of-1-bits/" },
  { order: 146, title: "Counting Bits", topic: "Bit Manipulation", difficulty: "Easy", leetcodeLink: "https://leetcode.com/problems/counting-bits/" },
  { order: 147, title: "Reverse Bits", topic: "Bit Manipulation", difficulty: "Easy", leetcodeLink: "https://leetcode.com/problems/reverse-bits/" },
  { order: 148, title: "Missing Number", topic: "Bit Manipulation", difficulty: "Easy", leetcodeLink: "https://leetcode.com/problems/missing-number/" },
  { order: 149, title: "Sum of Two Integers", topic: "Bit Manipulation", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/sum-of-two-integers/" },
  { order: 150, title: "Reverse Integer", topic: "Bit Manipulation", difficulty: "Medium", leetcodeLink: "https://leetcode.com/problems/reverse-integer/" }
];

module.exports = NEETCODE_150_PROBLEMS;
